#!/bin/bash

# This shell script generates a file called "s0init.4th" and "s1init.4th"
# s0init.4th is the bare minimum to crank up the clock speed and implement flowcontrol
# For S0 to load, you probably need a 50ms pause at the end of newlines
# After S0, you can turn on flow control and should be able to load the rest of the files at full speed

# Stage 0 initialization file - to be loaded with newline delays until flowcontrol can be established
{
  echo compiletoflash

  # First, get the clock speed up to 96 MHz
  ssed -Rf ss < mcg.4th
  echo fullspeed
  echo '\ Add a comment line ... it often gets garbled when the uart clock changes'

  # Now, initiate basic flow control
  # Forgone software flow control.  Now using CTS/RTS
  # ssed -Rf ss < swflowcontrol.4th

  # Add to init to automatically go to full speed and software flow control
  # echo ': init fullspeed ['"'"'] prompt hook-quit ! CR ." Running at 96MHz" CR ." XON/XOFF enabled" CR ';
  # Add to init to automatically go to full speed
  echo ': init fullspeed CR ." Running at 96MHz" CR ;'
  echo init
  ssed -Rf ss < fault.4th
  echo "' .fault irq-fault !"
  ssed -Rf ss < nvic.4th
  ssed -Rf ss < uart.4th
  echo "' uart0e-isr irq-uart0e !"
  echo uart0e-eint

  ssed -Rf ss < gpio.4th
  ssed -Rf ss < delay.4th
  ssed -Rf ss < timer.4th
  ssed -Rf ss < led.4th
  ssed -Rf ss < asciiart.4th
  ssed -Rf ss < init.4th
  ssed -Rf ss < ../../common/forth/disassembler-m3.4th
  ssed -Rf ss < struct.4th

  echo compiletoram

} > s0init.4th






